//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("salary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5ecb3e061053c64672f9809e8e948574 {
            get {
                object obj = ResourceManager.GetObject("5ecb3e061053c64672f9809e8e948574", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5ecb3e061053c64672f9809e8e9485741 {
            get {
                object obj = ResourceManager.GetObject("5ecb3e061053c64672f9809e8e9485741", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _965bf0ffaa83d1a76d7bcaf9c30c9436 {
            get {
                object obj = ResourceManager.GetObject("965bf0ffaa83d1a76d7bcaf9c30c9436", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aa17d176dd6c49775623c65db9ea15b2__1_ {
            get {
                object obj = ResourceManager.GetObject("aa17d176dd6c49775623c65db9ea15b2 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b0f2acb61b9a6546287fe63b1405e9d6 {
            get {
                object obj = ResourceManager.GetObject("b0f2acb61b9a6546287fe63b1405e9d6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b0f2acb61b9a6546287fe63b1405e9d61 {
            get {
                object obj = ResourceManager.GetObject("b0f2acb61b9a6546287fe63b1405e9d61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b0f2acb61b9a6546287fe63b1405e9d62 {
            get {
                object obj = ResourceManager.GetObject("b0f2acb61b9a6546287fe63b1405e9d62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com {
            get {
                object obj = ResourceManager.GetObject("pngwing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صDDDDDDDD {
            get {
                object obj = ResourceManager.GetObject("صDDDDDDDD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتFF {
            get {
                object obj = ResourceManager.GetObject("صورة واتFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتFF1 {
            get {
                object obj = ResourceManager.GetObject("صورة واتFF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتFF2 {
            get {
                object obj = ResourceManager.GetObject("صورة واتFF2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتFF3 {
            get {
                object obj = ResourceManager.GetObject("صورة واتFF3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_15_36_48_d5887ab8 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 15.36.48_d5887ab8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_15_361 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 15.361", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_15_39_02_8ec9a478 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 15.39.02_8ec9a478", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_15_391 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 15.391", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_15_392 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 15.392", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_19_10_26_d86b764f {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 19.10.26_d86b764f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_19_11_28_348b8d50 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 19.11.28_348b8d50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_19_12_23_4c5aa761 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 19.12.23_4c5aa761", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_19_12_58_083ac19f {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 19.12.58_083ac19f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_19_121 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 19.121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_19_122 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 19.122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_19_123 {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 19.123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_20_46_57_5e2d6d6d {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 20.46.57_5e2d6d6d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap صورة_واتساب_بتاريخ_2025_11_21_في_20_55_38_7cccfecf {
            get {
                object obj = ResourceManager.GetObject("صورة واتساب بتاريخ 2025-11-21 في 20.55.38_7cccfecf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
